version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 727646489067.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest 727646489067.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 727646489067.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"myapp-container","imageUri":"727646489067.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
